import type { Metadata } from "next";
import { TASA_Orbiter } from "next/font/google";
import "./globals.css";

const tasaOrbiter = TASA_Orbiter({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700", "800"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${tasaOrbiter.className} h-full antialiased bg-black`}
		>
			<body className="min-h-full flex flex-col">{children}</body>
		</html>
	);
}
